common:
  img_topic: "/left_camera/image"
  lid_topic: "/livox/lidar"
  imu_topic: "/livox/imu"
  img_en: 1
  lidar_en: 1
  ros_driver_bug_fix: false

extrin_calib:
  extrinsic_T: [-0.011, -0.02329, 0.04412]
  extrinsic_R: [1, 0, 0,
                0, 1, 0,
                 0, 0, 1]
  # extrinsic_R:
  #   [ 0.8660254,  0.0, -0.5,
  #     0.0,        1.0,  0.0,
  #     0.5,        0.0,  0.8660254 ]
  # Rcl: [0.00610193,-0.999863,-0.0154172,
  #       -0.00615449,0.0153796,-0.999863,
  #       0.999962,0.00619598,-0.0060598] 
  Rcl: [-0.00321, -0.99995, 0.00985, 
         0.41865, -0.01029, -0.90809, 
         0.90814, 0.00121, 0.41866]
 

# Rcl: [-0.01336,-0.99991,  -0.00201,   
#     0.42109,-0.00380, -0.90701,
#     0.90692,-0.01296,  0.42110] 

  Pcl: [-0.04453, -0.02779, 0.02164]
  # Pcl: [0.0194384, 0.104689,-0.0251952]

# Pcl: [-0.00092,-0.05236,-0.03560]
time_offset: 
  imu_time_offset: 0.0
  img_time_offset: 0.1
  lidar_time_offset: 0.0
  exposure_time_init: 0.0

preprocess:
  hilti_en: false
  point_filter_num: 1
  filter_size_surf: 0.1
  lidar_type: 1 # Livox Avia LiDAR
  scan_line: 4
  blind: 0.8
  feature_extract_enabled: false

vio:
  max_iterations: 5
  outlier_threshold: 1000 # 78 100 156 #100 200 500 700 infinite
  img_point_cov: 100 # 100 1000 
  patch_size: 8
  patch_pyrimid_level: 4
  grid_size: 5
  grid_n_height: 17
  normal_en: true
  raycast_en: false
  inverse_composition_en: false
  exposure_estimate_en: true
  inv_expo_cov: 0.1
visual:
  image_stride_normal: 3
  image_stride_degenerate: 1
  keyframe_trans_thresh: 1.0
  keyframe_rot_thresh: 30.0
  keyframe_scale_min: 0.3
  max_points_per_voxel: 30
  long_term_max_points_per_voxel: 5
  point_max_age: 50
  downsample_ratio: 0.5
  patch_pyrimid_level: 4
  patch_size: 8

imu:
  imu_en: true
  gravity_est_en: true
  ba_bg_est_en: true
  imu_int_frame: 30
  acc_cov: 0.8 # 0.2
  gyr_cov: 0.5 # 0.5
  b_acc_cov: 0.0001 # 0.1
  b_gyr_cov: 0.0001 # 0.1

lio:
  max_iterations: 5
  dept_err: 0.02
  beam_err: 0.15
  min_eigen_value: 0.0025 # 0.005
  sigma_num: 3
  degen_sigma_min: 0.07
  degen_valid_ratio: 0.15
  degen_avg_residual: 0.013
  degen_count_thresh: 3
  voxel_size: 0.5
  max_layer: 2
  max_points_num: 50
  layer_init_num: [5, 5, 5, 5, 5]

local_map:  
  map_sliding_en: true
  half_map_size: 100
  sliding_thresh: 4

long_term_map:
  map_sliding_en: true
  half_map_size: 400
  sliding_thresh: 20

uav:
  imu_rate_odom: false
  gravity_align_en: true

debug:
  plot_time: -10
  frame_cnt: 6

publish:
  dense_map_en: true
  pub_effect_point_en: false 
  pub_plane_en: false
  pub_scan_num: 1
  blind_rgb_points: 0.0

evo:
  seq_name: "CBD_Building_01"
  pose_output_en: false

pcd_save:
  pcd_save_en: false
  type: 0 # 0: World Frame, 1: Body Frame;
  colmap_output_en: false # need to set interval = -1
  filter_size_pcd: 0.15
  interval: -1
  # how many LiDAR frames saved in each pcd file;
  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

image_save:
  img_save_en: false
  interval: 1
