common:
  img_topic: "/left/image_raw"
  lid_topic: "/os1_cloud_node1/points"
  imu_topic: "/imu/imu"
  img_en: 1
  lidar_en: 1
  ros_driver_bug_fix: false

extrin_calib:
  extrinsic_T: [-0.050, 0.000, 0.055]
  extrinsic_R: [1, 0, 0, 0, 1, 0, 0, 0, 1]
  # NTU_VIRAL
  Rcl: [0.0218308, 0.99976, -0.00201407,
        -0.0131205, 0.00230088, 0.999911,
        0.999676, -0.0218025, 0.0131676]
  Pcl: [0.122993,  0.0398643, -0.0577101]

time_offset:
  lidar_time_offset: -0.1
  imu_time_offset: 0.0
  img_time_offset: 0.0
  exposure_time_init: 0.0

preprocess:
  hilti_en: false
  point_filter_num: 3
  filter_size_surf: 0.1
  lidar_type: 3 # Ouster
  scan_line: 16
  blind: 1.0
  feature_extract_enabled: false

vio:
  max_iterations: 5
  outlier_threshold: 1000 # 78 100 156 #100 200 500 700 infinite
  img_point_cov: 100 # 100 1000 
  patch_size: 8
  patch_pyrimid_level: 3
  grid_size: 5
  grid_n_height: 17
  normal_en: true
  raycast_en: false
  inverse_composition_en: false
  exposure_estimate_en: true
  inv_expo_cov: 0.1

visual:
  image_stride_normal: 3
  image_stride_degenerate: 1
  keyframe_trans_thresh: 1.0
  keyframe_rot_thresh: 30.0
  keyframe_scale_min: 0.3
  max_points_per_voxel: 30
  long_term_max_points_per_voxel: 10
  point_max_age: 50
  downsample_ratio: 0.5
  patch_pyrimid_level: 3
  patch_size: 8

imu:
  imu_en: true
  gravity_est_en: true
  ba_bg_est_en: true
  imu_int_frame: 30
  acc_cov: 0.5 # 0.2
  gyr_cov: 0.3 # 0.5
  b_acc_cov: 0.0001 # 0.1
  b_gyr_cov: 0.0001 # 0.1

lio:
  max_iterations: 5
  dept_err: 0.02
  beam_err: 0.01
  min_eigen_value: 0.0025 # 0.0025
  sigma_num: 3
  degen_sigma_min: 0.07
  degen_valid_ratio: 0.15
  degen_avg_residual: 0.12
  degen_count_thresh: 3
  voxel_size: 0.5
  max_layer: 2
  max_points_num: 50
  layer_init_num: [5, 5, 5, 5, 5]

local_map:  
  map_sliding_en: true
  half_map_size: 100
  sliding_thresh: 5

long_term_map:
  map_sliding_en: true
  half_map_size: 400
  sliding_thresh: 20

uav:
  imu_rate_odom: false
  gravity_align_en: false

debug:
  plot_time: -10
  frame_cnt: 6

publish:
  dense_map_en: true
  pub_effect_point_en: false 
  pub_plane_en: false
  pub_scan_num: 1
  blind_rgb_points: 0.0

evo:
  seq_name: "eee_01"
  pose_output_en: true

pcd_save:
  pcd_save_en: false
  type: 0 # 0: World Frame, 1: Body Frame;
  colmap_output_en: false # need to set interval = -1
  filter_size_pcd: 0.15
  interval: -1
  # how many LiDAR frames saved in each pcd file;
  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

image_save:
  img_save_en: false
  interval: 1
